"use client";
import { useNavigate, useLocation, useSearchParams } from "react-router-dom";
import { useEffect, useState } from "react";
import { keepPreviousData, useQuery } from "@tanstack/react-query";
import { patientApiServices } from "@/api-services/patient/api";
import CustomPagination from "@/components/common/CustomPagination";
import { ILetter, ILettersResposne } from "@/api-services/patient/types";
import LetterDataListSkeleton from "./LetterDataListSkeleton";
import LetterDataList from "./LetterDataList";

const LettersWrapper = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const [searchParams] = useSearchParams();
  const [page, setPage] = useState(() =>
    parseInt(searchParams.get("page") || "1", 10),
  );

  useEffect(() => {
    const params = new URLSearchParams();
    Object.entries({
      page,
    }).forEach(([key, value]) => {
      if (value !== undefined && value !== null) {
        params.append(key, String(value));
      }
    });
    navigate(`${location.pathname}?${params.toString()}`, { replace: true });
  }, [page, navigate, location.pathname]);

  const { data, isLoading, isError, error } = useQuery({
    queryKey: ["getLetters", page],
    queryFn: () => patientApiServices.getLetters<ILettersResposne>(page),
    placeholderData: keepPreviousData,
  });

  if (isError) {
    return (
      <div className="text-sm">
        <span className="font-medium text-destructive">
          Failed to load results {" : "}
        </span>
        <span className="text-muted-foreground">
          {error.message || "Please try again later."}
        </span>
      </div>
    );
  }

  const DEMO_CONTENT = "This letter was generated by the Demo Data Letter generation tool.";

  const dataList = (data?.data || [])
    .filter(
      (l) =>
        !l.attributes.is_archived &&
        !l.attributes.is_deleted &&
        l.content.trim() !== DEMO_CONTENT,
    )
    .reduce<ILetter[]>((acc, letter) => {
      const existing = acc.find(
        (l) => l.attributes.letter_id === letter.attributes.letter_id,
      );
      if (!existing) return [...acc, letter];
      const keepNew =
        letter.attributes.is_active_version ||
        (!existing.attributes.is_active_version &&
          letter.attributes.letter_version > existing.attributes.letter_version);
      return keepNew
        ? acc.map((l) => (l.attributes.letter_id === letter.attributes.letter_id ? letter : l))
        : acc;
    }, [])
    .sort(
      (a, b) =>
        new Date(b.effectiveAt).getTime() - new Date(a.effectiveAt).getTime(),
    );
  const paginationMeta = data?.meta || null;

  return (
    <div className="w-full space-y-5">
      <div>
        <h1 className="text-2xl font-bold tracking-tight font-serif">
          Letters
        </h1>

        <p className="text-sm text-muted-foreground mt-1">
          Review and manage all medical letters and notices.
        </p>
      </div>

      {isLoading ? (
        <LetterDataListSkeleton />
      ) : (
        <LetterDataList letterList={dataList} />
      )}

      {!isLoading && paginationMeta && (
        <CustomPagination
          pagination={{
            page,
            limit: paginationMeta?.per_page,
            total: paginationMeta?.total,
            totalPages: paginationMeta?.last_page,
          }}
          onPageChange={setPage}
        />
      )}
    </div>
  );
};

export default LettersWrapper;
